version: "3"
services:
  emart-eureka-service:
    image: emart-eureka-service:latest
    ports:
      - "9999:9999"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure